### ISSUE TITLE
Namespace mismatch error with scribble/srcdoc

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#103]
I appear to be getting a new, different error when attempting to run cover on modules that use `scribble/srcdoc`:

```
$ raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p alexis-collection-lens
generating test coverage for ("/home/travis/build/lexi-lambda/alexis-collection-lens/collection/lens/private/sandbox.rkt" "/home/travis/build/lexi-lambda/alexis-collection-lens/collection/lens/private/test/doc-coverage.rkt" "/home/travis/build/lexi-lambda/alexis-collection-lens/collection/lens.rkt" "/home/travis/build/lexi-lambda/alexis-collection-lens/info.rkt" "/home/travis/build/lexi-lambda/alexis-collection-lens/scribblings/main.scrbl" "/home/travis/build/lexi-lambda/alexis-collection-lens/travis-racket/main.rkt")
require: namespace mismatch;
 reference to a module that is not available
  reference phase: 0
  referenced module: "/home/travis/racket/collects/racket/private/kw.rkt"
  referenced phase level: 0
  in: #%app
  context...:
   /home/travis/.racket/snapshot/pkgs/cover/strace.rkt:41:4
   /home/travis/.racket/snapshot/pkgs/cover/cover.rkt:167:4: cover-compile
```

As the message suggests, I'm having this issue with the latest update to my `alexis-collection-lens` package, if you'd like to try and reproduce it.

**Comment by florence** [comment]
I'm not able to reproduce this locally. What version of Racket are you on? And which version of cover?

**Comment by lexi-lambda** [comment]
I'm running off of Racket HEAD with the latest version of cover:

```
$ racket --version
Welcome to Racket v6.2.900.17.
$ raco pkg update cover
Resolving "cover" via http://pkgs.racket-lang.org
No updates available
```

I've gotten this error both on my local machine and in [CI](https://travis-ci.org/lexi-lambda/alexis-collection-lens/jobs/80056524), so I don't think it's just some weird config I have on my machine.

**Comment by florence** [comment]
Could you try using the version of Cover on its git HEAD? I suspect this has been fixed. (We're stuck on a release right now. I intended to release today, but...)

**Comment by lexi-lambda** [comment]
Hmm, you're right, it seems to work fine on master. Sorry for the noise!
