### ISSUE TITLE
Allow for linking to line numbers in HTML output

### ISSUE THREAD

**Issue by florence** [florence/cover#114]
something like `cover/info.rkt#L10` should take you to line 10 of the coverage info for that file.

**Comment by jackfirth** [comment]
:+1:

**Comment by florence** [comment]
@jackfirth it will be a while before I get to this. You want to do it? :P

**Comment by florence** [comment]
Added by  e997e6d thanks to @jsmaniac !

**Comment by jackfirth** [comment]
Seems I've been beaten to it :) Awesome!
