### ISSUE TITLE
Missed coverage when using in-indexed in for loops

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#120]
The following program should be fully covered, but cover reports missing coverage:
```racket
#lang racket

(define (indexed lst)
  (for/list ([(x i) (in-indexed lst)])
    (cons i x)))

(indexed '(a b c d e))
```

Specifically, this expression is marked as uncovered:
```racket
 (for/list ([(x i) (in-indexed lst)])
;             ^ this x is apparently uncovered
```

I’m not sure if this is an issue with cover or with `in-indexed`, but I figured reporting it here probably makes at least a little sense.

**Comment by florence** [comment]
This is likely a manifestation of https://github.com/racket/errortrace/issues/2

**Comment by florence** [comment]
(I swear I'll get around to fixing that someday...)

**Comment by florence** [comment]
Fixed this in the errortrace repo
