### ISSUE TITLE
Typed Racket `provide` marked uncovered

### ISSUE THREAD

**Issue by jackfirth** [florence/cover#121]
I have a utility module that provides a single function. The entire module is marked covered *except* for the `provide` line (detailed report here https://coveralls.io/builds/5872557/source?filename=syntax%2Fwarn%2Fprivate%2Fstring-pad.rkt#L3). Is this related to #88?

**Comment by florence** [comment]
Yes in the sense that its probably the same resolution: TR is likely dropping source locations somewhere.  I'm not sure though.

**Comment by florence** [comment]
I take it back, after looking a the expansion of that module I suspect this is a problem with how `errortrace` handles covering `#%provide` combined with oddities of TR expansion. I'll fix soon.

**Comment by florence** [comment]
This being fixed by https://github.com/racket/errortrace/pull/9
