### ISSUE TITLE
`directory-exists?` internal error

### ISSUE THREAD

**Issue by takikawa** [florence/cover#122]
```
$ raco cover -b -p typed-racket-lib -p typed-racket-test
directory-exists?: contract violation
  expected: path-string?
  given: #f
  context...:
   /home/asumu/plt/racket-git/racket/share/pkgs/cover/cover/raco.rkt:162:0: expand-directories14
   /home/asumu/plt/racket-git/racket/share/pkgs/cover/cover/raco.rkt:83:4
   /home/asumu/plt/racket-git/racket/share/pkgs/cover/cover/private/shared.rkt:28:0: with-intercepted-logging
   (submod /home/asumu/plt/racket-git/racket/share/pkgs/cover/cover/raco.rkt main): [running body]
   /home/asumu/plt/racket-git/racket/collects/raco/raco.rkt: [running body]
```

**Comment by florence** [comment]
Hrmmm... I think this is bug with `command-line`. `-p` is as `#:once-any` argument and its being given twice.

Cover is being given the second `-p` as a normal argument not a flag. cover should give a better error message on non-existent packages though.

**Comment by takikawa** [comment]
Ah thanks, that explains why I was confused. It does do the expected thing when I provide both packages as normal arguments with only one `-p`.

**Comment by florence** [comment]
I've moved this issue to racket/racket/issues/1342
