### ISSUE TITLE
Unbound identifier error when running cover on HEAD on functional

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#126]
<sub>I always feel weird submitting bug reports for cover because I never know enough about anything to really submit reports with anything approaching decent information, but anyway...</sub>

Running cover on [functional](https://github.com/lexi-lambda/functional) seems to suddenly be failing with a somewhat arcane error:

```
$ raco cover -bf coveralls -d $TRAVIS_BUILD_DIR/coverage -p functional-lib functional-test
cover: instrumenting: /home/travis/build/lexi-lambda/functional/functional-lib/data/applicative.rkt
/home/travis/build/lexi-lambda/functional/functional-lib/data/monad.rkt
/home/travis/build/lexi-lambda/functional/functional-lib/data/applicative.rkt
/home/travis/.racket/snapshot/pkgs/cover/cover/strace.rkt:27:19: #%app: unbound identifier at phase 2;
 also, no #%app syntax transformer is bound
  at: #%app
  in: (#%app unsafe-vector*-set! cover-coverage-vector (quote 439) (quote #t))
  context...:
   standard-module-name-resolver
   .../more-scheme.rkt:261:28
```

[You can see the Travis build logs here](https://travis-ci.org/lexi-lambda/functional/jobs/134308873#L557), but I can also reproduce the issue locally by installing functional and running the following command:

```
$ raco cover -bp functional-lib functional-test
```

**Comment by florence** [comment]
This was fixed by https://github.com/florence/cover/pull/124/files but I forgot to release it. I've released it, so this should go away whenever the pkg server updates.
