### ISSUE TITLE
Cover doesn't mark log message and argument expressions as covered

### ISSUE THREAD

**Issue by jackfirth** [florence/cover#136]
Given this program:

```racket
#lang racket
(define-logger foo)
(log-foo-warning "blah ~v" 'foo)
```

Running `raco cover` produces the following:

<img width="360" alt="screen shot 2017-07-22 at 1 45 37 am" src="https://user-images.githubusercontent.com/8175575/28489752-7ea0407e-6e7f-11e7-8875-9b134a2424de.png">

I suspect this is caused by srcloc issues with the macros produced by `define-logger`.

**Comment by florence** [comment]
Looking at the expansion this is actually correct. The expansion gives:

```
(let-values (((l) foo-logger))
        (if (#%app log-level? l 'warning 'foo)
          (let-values ()
            (#%app
             log-message
             l
             'warning
             (#%app format '"blah ~v" 'foo)
             (#%app current-continuation-marks)))
          (#%app void)))
```

Which seams to avoid logging anything if the log-level isn't set to warning.

in the program:
```
#lang racket
(define-logger foo)
(make-log-receiver foo-logger 'warning)
(log-foo-warning "blah ~v" 'foo)
```

the message is covered.
