### ISSUE TITLE
Failing test on package build server

### ISSUE THREAD

**Issue by jackfirth** [florence/cover#137]
The [test transcript](http://pkg-build.racket-lang.org/server/built/test-fail/cover.txt) points to the `tests/main.rkt` module.

**Comment by florence** [comment]
Its treating a non-empty stderr as a test failure. I wonder why this hasn't failed in the past... Thanks for the report!

**Comment by florence** [comment]
This should be fixed by 42a9ff296b6180bf6dcfc75d0ef9a9729d9f0762. Will wait until next pkg build to close.

**Comment by jackfirth** [comment]
Success!

<img width="1132" alt="screen shot 2017-08-24 at 10 16 06 am" src="https://user-images.githubusercontent.com/8175575/29678953-45c1d36c-88b5-11e7-9e11-edb797a8f6e1.png">
