### ISSUE TITLE
Cover reveals hidden lines in ISL files

### ISSUE THREAD

**Issue by florence** [florence/cover#145]

**Comment by florence** [comment]
The core issue here is that ISL has these sneak hidden lines at the top of the file that drracket knows to hide, but cover knows to ignore these lines. *but*, when all lines are ignored cover behaves oddly, assuming that every character is passed the end of the file.

**Comment by florence** [comment]
@tov once CI passes I'll merge this into the release. It should be out by tomorrow evening; if you have your students update things should work better!

**Comment by tov** [comment]
Thanks! It's actually happening on GitHub Actions, which means I install it
fresh each time, so I should get it as soon as it’s on master.

J
