### ISSUE TITLE
Support the command line options from `raco test`

### ISSUE THREAD

**Issue by samth** [florence/cover#18]
You can specify `-p` to test a package, or `-c` to test a collection, etc. This would be helpful for cover too.

**Comment by florence** [comment]
gah, We already grabbed the `-p` name, but I'll look into adding these. Does `raco test` do anything special when it tests a package or collection other than look up its location via `collection-file-path` and `pkg-directory`?

**Comment by samth** [comment]
I think you should switch `-p` now while you have the chance.

**Comment by samth** [comment]
Here's the implementation of `raco test`: https://github.com/racket/compiler/blob/master/compiler-lib/compiler/commands/test.rkt

It looks like it calls `collection-paths` and `pkg-directory`, respectively.

**Comment by florence** [comment]
Given the problems in #21 supporting `test-omit-paths` from an info.rkt is the next priority here.

**Comment by florence** [comment]
Both `test-omit-paths` and `test-command-line-arguments` are now supported. Future support should be given its own issue.
