### ISSUE TITLE
Doesn't respect Ctrl-C properly

### ISSUE THREAD

**Issue by samth** [florence/cover#19]
- Run cover on a big directory.
- Hit Ctrl-C
- Note that it doesn't actually stop.

**Comment by samth** [comment]
You really want to use `exn:fail?` instead.

**Comment by florence** [comment]
What about cases like `exn:misc:match?` or `(raise 3)`? Are these just idiomatically wrong, and so should not be concerned about?

**Comment by samth** [comment]
`exn:misc:match` should be an `exn:fail`. `(raise 3)` is a silly program.

You could do `(or (not (exn? x) (exn:fail? x))`.
