### ISSUE TITLE
Remove flag name conflicts with raco test

### ISSUE THREAD

**Issue by florence** [florence/cover#22]
Issue #18 shows we need to do this, and now.

**Comment by rpless** [comment]
We currently collide on -c (coverage) and -e. In raco test -c interprets the argument as a collection and -e treats any output to stderr as a test failure. I think we should change -c to -f (--format). But I'm not sure I want to change -e.

**Comment by florence** [comment]
How about `-n`/`--no-output-for`?

**Comment by rpless** [comment]
Done at 115acbd78
