### ISSUE TITLE
`for` macros get run but show up as not run

### ISSUE THREAD

**Issue by rpless** [florence/cover#27]
The identifier for individual elements of sequences/streams/whatever comes up as not run. This makes it look like coverage is not complete for areas of the code that actually do get run. @florence ideas?
Example: https://coveralls.io/files/424277798#L115

**Comment by florence** [comment]
Arguably this is a bug in racket: either in `stacktrace@` or in `for`. But it also could be a bug in how we instrument code. I will ask help of minds that know more...

**Comment by florence** [comment]
Using `in-list`, `in-range` and friends seems to negate this. Which is the proper style I believe anyways.

**Comment by greghendershott** [comment]
It would make a good README tip:

Although intended as a coverage tool, in this case cover is giving you an Optimization Coach tip. [Using an `in-list` application as the sequence in a `for` loop gives better performance](http://docs.racket-lang.org/reference/sequences.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._in-list%29%29).

**Comment by florence** [comment]
It should probably go in the `gotcha`s portion of the scribble docs as well.

**Comment by florence** [comment]
Finally getting around to adding this:

`in-hash` still has this problem

This is a complex macro expansion issue, and is not something we can really fix. I will add it to the README and Gotcha's, then close this.

**Comment by florence** [comment]
Dealt with by 824c6bc
