### ISSUE TITLE
Running cover on default libraries (install via `make` on HEAD) errors

### ISSUE THREAD

**Issue by florence** [florence/cover#28]
Examples:

`raco cover -c net`
`raco cover -c compiler`

Error looks like:
```
link: bad variable linkage;
 reference to a variable that is not a procedure or structure-type constant across all instantiations
```

**Comment by florence** [comment]
This appears to be because of recursive require paths:

for example: net has a build dependency on scribble/manual which has a dependency on planet which has a decency on net. I have no clue how to fix this without recompiling everything. that depends on a package being tested.

**Comment by florence** [comment]
This is being put under "not our problem, cyclic dependencies are bad, mkay?"

The practical fix is to add things to `cover-omit-paths` or cover more things.

**Comment by samth** [comment]
Is this something that can be demonstrated without `cover`, ie just by using `stacktrace`? 

I feel like this is something that Racket could provide more help with.

@mflatt, any thoughts here?

**Comment by florence** [comment]
This should happen if you run tell raco test to compile with strace then do raco test -c net
