### ISSUE TITLE
coverage/index.html should sort by name (or coverage)

### ISSUE THREAD

**Issue by zenspider** [florence/cover#31]
I don't have a vested interest in which sorting to use at this point, but it would help immensely if the index page was sorted by name/path. Later options could sort it by coverage %, but that shouldn't hold up a quick sort.

I was told to ping @rpless specifically. :)

I'll try to track this down myself if you'd rather.

**Comment by florence** [comment]
@rpless  you wanted to do this on the javascript side, no?

**Comment by rpless** [comment]
Yes, my plan is to implement sorting on the client side. That way we can dynamically sort by any of the columns. Hopefully, I'll have some time during the next round of #snowpocalypse on Thursday or Friday to take a crack at it.

**Comment by zenspider** [comment]
I'm not married to this PR so feel free to close it as-is. I'm running it locally which has solved my immediate problems so I'm good.

**Comment by rpless** [comment]
I may have time tonight after all. What do you think of sorting on the filename as opposed to the full path? Does that make more or less sense to people?

**Comment by zenspider** [comment]
Either would work for me as I'm doing flat directories, but I would think filename would be confusing to those who are actually using structured directories.

**Comment by florence** [comment]
The sorting should probably sort based on the full path. Its how I tend to look for stuff in my file system, so it should be the same here.
