### ISSUE TITLE
Is the raw format missing some analysis done in the html and json formats?

### ISSUE THREAD

**Issue by greghendershott** [florence/cover#51]
Given /tmp/r.rkt:

```
#lang racket
(define (f) 1)
(define (g) 2)
(module+ test (f))
```

When I do `raco cover -f raw -d /tmp r.rkt` I get:

```
#hash(("/tmp/r.rkt"
       .
       ((#t #(struct:srcloc "/tmp/r.rkt" #f #f 14 14))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 29 14))
        (#f #(struct:srcloc "/tmp/r.rkt" #f #f 41 1))  ;; <-- OK
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 23 1))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 44 18))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 58 3))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 59 1))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 38 1))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 26 1))
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 1 62))))) ;; <-- Huh?
```

This corresponds to the body of `g` which isn't called: 

```
        (#f #(struct:srcloc "/tmp/r.rkt" #f #f 41 1))  ;; <-- OK
```

However the last line says that the entire file _is_ covered, which seems weird:

```
        (#t #(struct:srcloc "/tmp/r.rkt" #f #f 1 62))))) ;; <-- Huh?
```

If I wanted to use the raw format, should I simply check for and discard that one bogus item, covering the entire file?

Or is there other processing done to make the HTML and JSON formats, that I should be aware of?

---

The background to this: Re [making use of cover in racket-mode](https://github.com/greghendershott/racket-mode/issues/51), it occurred to me that a vastly simpler way to handle this is to `system` out to `raco cover`, `read` the raw file, and convert it to an Elisp data structure.  No need to futz with the evaluation core of racket-mode. Then, the bulk of the work is the usual Emacs "UI" stuff like putting green or red overlays in the source file, or whatever.

But this small bug (?) made me want to ask, and make sure you would be OK with the raw format really being used, as opposed to it being a development aid or whatever.

**Comment by florence** [comment]
Correct, there is extra analysis done by `make-covered?`.

In essence the raw structure determining if a point is covered requires finding the deepest point in that map which spans over that point. The logic for this, and other such considerations is horribly complicated. In essence nothing should look at raw directly and instead it should use `make-covered?`.  `make-covered?` also handles things like marking comments and some submodules `irrelevant` to code coverage.

the `--raw` format really only exists for debugging purposes.

**Comment by florence** [comment]
On a side note there is a huge API change coming for cover, with the express intention of having cover be used for backing both `racket-mode` and DrRacket's code coverage. `make-covered?` probably wont change, but the API for running files will be completely different.

**Comment by florence** [comment]
>  it occurred to me that a vastly simpler way to handle this is to system out to raco cover, read the raw file,

This is probably a terrible idea. `make-covered?` is very complicated and does things like re-lexes the input file. Also If you add cover directly to module evaluation then REPL interactions will be able to effect code coverage (a huge plus in my book).

Also yes the raw format is really just for debugging.
