### ISSUE TITLE
Coveralls tests fail if git is not found

### ISSUE THREAD

**Issue by florence** [florence/cover#57]
See http://pkg-build.racket-lang.org/server/built/test-fail/cover.txt

This is causing our tests to fail on the build server

**Comment by rpless** [comment]
Does the package server just do a `git checkout`? If so, I'll write a thing to parse refs and branches straight from the `.git` folder. Otherwise it might not work either way.

**Comment by samth** [comment]
It uses the package system itself (which has an implementation of `git
clone`).
​

**Comment by florence** [comment]
The coveralls module should check if its in a git checkout (or if `git`
exists) and do something sane if it doesn't. (Maybe error, or just exclude
that info from the output).

**Comment by rpless** [comment]
Coveralls has been moved to its own repo, see the issue there.
