### ISSUE TITLE
sexp formatter?

### ISSUE THREAD

**Issue by zenspider** [florence/cover#66]
I've been told (by greg?) that the raw output is "too raw" to actually be used because many of the coverage calculations haven't been made yet. I'd like a formatter that outputs a sexp of calculated coverage info that can be used as-is by emacs or other tools.

Back in the day I had an emacs mode called "rcov-overlay" that would take ruby coverage data and use the marshaled data to apply a background color overlay to uncovered code. It took a simple data structure of `((start-byte stop-byte color) ...)` (created by post-processing the marshal data) and was quite easy to work with.

**Comment by florence** [comment]
As I mentioned to @greghendershott the raw format is for debugging only. In fact it has been completely removed from the documentation and should not be used.

Instead one should use `test-files!` and `make-covered?` from the racket API.

Those can be used as is. For general IDE support you will want to wait for 2.0, which adds thread safety and better namespace reflection. (We need @mflatt's new macro expander first).

If you don't need a REPL or something of that ilk, `test-files!` and `make-covered?` will work fine.
Eventually we will expose a way to just ask for the expression and branch coverage directly from the racket API, but that is also waiting on 2.0.

**Comment by florence** [comment]
Will be fixed by #67

**Comment by florence** [comment]
@zenspider Does the new racket API in PR #70 work for your purposes?
