### ISSUE TITLE
Support Codecov

### ISSUE THREAD

**Issue by rpless** [florence/cover#76]
I've opened this issue to track Codecov support.

I think this is also a good time to discuss pulling CI service coverage reports into there own libraries.

**Comment by florence** [comment]
Here is what I think we want in the long run:

* A better Racket API that can take the coverage report and synthesize things like "expression" and "branch" coverage.

* A Standard text output format for anything that isn't in Racket, that contains those synthesized reports.

* All other formats, sans HTML in their own libraries.

Given that the longest term plan for cover is to have it replace the coverage stuff in `errortrace`, and go in the main distribution, I think the last bullet is key.

Also here is another question: Do we support Codecov's JSON format, or do we handle bullet 2 (I Have an extensible proposal for that), and ask them to support that format?

**Comment by rpless** [comment]
All of Codecov's current supported formats appear to be line based. I think at least in the short term we should just dump coverage json like we do for Coveralls. I need to dive into it a little more, but I imagine Coveralls and Codecov will only vary in synthesizing Json (a very small part of the code). Most of the underlying functions would probably be the same. Maybe we should have a separate package called `cover-ci`? That would provide Coveralls and Codecov and I guess any other coverage reporting services that may crop up.

**Comment by florence** [comment]
I'm not sure if we want `cover-ci`, or to have separate repos... I think the former sounds nice, but the second appeals to my inner type A... Lets go with the former. 

They will probably have some shared pre-processing stuff for line-base format. Something like `coverage->lines-coverage`. That should probably go into the core of cover's api?

**Comment by rpless** [comment]
The main parts of these service based coverage formats are:
- converting coverage data to a line based format
- folding that into the correct format for the service
- Posting that data

If we make the core API support converting to line based formats, then it makes more sense to have two separate repos. But I'm not convinced that converting to line based coverage belongs in the core API. Thus far the service based formats are the only ones that care about it, not the base formats and not `errotrace`. I don't think it makes sense to have it in the core API.

**Comment by florence** [comment]
How about this: put the line coverage tools in a `cover-ci` library, but under the require path  `cover/line-format` or something, so that if we want to move it we can with zero breaking changes.

**Comment by rpless** [comment]
Can we do that without requiring the user to `raco link` that path? I'm unaware of any other way to provide the line formatter in the way you have described.

**Comment by florence** [comment]
yes. require paths and package names have more or less no relation, and require paths are can be use by multiple packages.

Essentially we create a package whos top level has an info.rkt with a collection type of `'multi` (i think) then have a `cover` directory where all the code goes.

**Comment by florence** [comment]
Cover should actually be set up like this anyways. i just haven't gotten around to it.

**Comment by florence** [comment]
As part of this issue I would like to actually migrate cover to codecov

**Comment by florence** [comment]
https://github.com/rpless/cover-codecov

It works!
