### ISSUE TITLE
Error on modules with nested submodules

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#78]
When running cover on Racket 6.1.1, I get the following error:

```
require: unknown module
  module name: #<resolved-module-path:(submod 'struct test updaters)>
  context...:
   /Users/alexis/Library/Racket/6.1.1/pkgs/cover/cover.rkt:171:4: cover-compile
   standard-module-name-resolver
   /Users/alexis/Library/Racket/6.1.1/pkgs/cover/cover.rkt:53:0: test-files!7
   (submod /Users/alexis/Library/Racket/6.1.1/pkgs/cover/raco.rkt main): [running body]
   /Applications/Racket v6.1.1/collects/raco/raco.rkt: [running body]
   /Applications/Racket v6.1.1/collects/raco/main.rkt: [running body]
```

Breaking master on 6.1.1 is fine, but maybe add a version exception to the package server?

**Comment by jackfirth** [comment]
I've gotten this sporadically as well

**Comment by florence** [comment]
Interesting... Do you have example where this happens? (The error here may be misleading as to what is happening)

**Comment by florence** [comment]
Also does this only happen on 6.1.1, but not on the nightly builds? I'm unaware of any breaking changes between 6.1.1 and 6.2 that would cause this.

**Comment by lexi-lambda** [comment]
See https://travis-ci.org/lexi-lambda/racket-alexis/builds/69685471. It only seems to happen on 6.1.1, not 6.2 or HEAD. Upon further inspection, however, I can't reproduce it for all packages, but `alexis-util` triggers it consistently. Note that `raco test` runs fine, though—only `raco cover` fails.

**Comment by jackfirth** [comment]
Anecdotally, I was able to fix this problem by specifying that cover should ignore the info.rkt files and .scrbl files with `test-omit-paths` in the package's info. Raco test seems to ignore those files by default while raco cover doesn't.

**Comment by florence** [comment]
@jackfirth Cover intentionally includes .scbl files to support things like `scribble/lp`. I'll start ignoring the info.rkt's.

@lexi-lambda do you mean the failure is sometimes nondeterministic? Or that only some modules trigger it? Also does @jackfirth's workaround fix this for you? I still suspect some kind of strange expansion bug...

Both: Does this error only happen with nested submodules?

**Comment by florence** [comment]
It seems that errortrace (which cover uses internally) has the same problem. If I run `private/tests/struct.rkt` from @lexi-lambda's example in DrRacket on 6.1.1 I get:

v6.1.1/share/pkgs/errortrace-lib/errortrace/errortrace-lib.rkt:434:2: require: unknown module
  module name: #<resolved-module-path:(submod 'anonymous-module test updaters)>

I still can't minimal test case, but this is most definitely either an errortrace bug or an expander bug. I will investigate more fully, unless @mflatt has any magic insights?

**Comment by lexi-lambda** [comment]
Ah! I'm stupid. I was racking my mind trying to think "where could I be using submodules, since I didn't make any changes recently involving them" when I realized *that's exactly what my last commit did*, only involving submodules nested inside a `test` submodule.

The change in question is https://github.com/lexi-lambda/racket-alexis/commit/23141965df8364235ca433f5e894fad14ae6d0c6. What's curious is that it already used a single nested submodule, but now it uses three. It's also a little odd that it work under 6.2 but not 6.1.1. Maybe I'll just have to disable that test on 6.1.1 if it's an expander or errortrace bug.

Either way, this doesn't appear to be a cover error; sorry for the noise!

**Comment by florence** [comment]
Don't worry! Cover exposes a lot of bugs :) I'll leave this open until I track down where the actual bug is.

**Comment by florence** [comment]
This is clearly a bug in errortrace. Will need to be fixed there.
