### ISSUE TITLE
Support new raco test options

### ISSUE THREAD

**Issue by florence** [florence/cover#82]
Raco test now supports regex's in `test-omit-paths`, and a `test-include-paths` option. We should too.

**Comment by jackfirth** [comment]
Would it be a good idea to support this at the command line too somehow? I can't rely on this in some of my libraries because they're meant to be compatible with versions of racket that don't support this in the info.rkt specification just yet.

**Comment by florence** [comment]
Cover only supports racket 6.1.1 and later, which all support info.rkt's, so this should be a non-issue.

**Comment by jackfirth** [comment]
Does 6.1.1 support regexps in test-omit-paths?

**Comment by florence** [comment]
No, I don't believe it does.

The only reason I hesitate to add CLI flags for this is because I worry about deviating too far from the `raco test` API. @rpless thoughts?

**Comment by rpless** [comment]
My preference would be to deviate from `raco test` as little as possible.

**Comment by florence** [comment]
@jackfirth It looks like cover already supports this. See covers `--include-extensions` flag.

Cover now supports `test-include-paths` and `cover-include-paths` as of 216c23523, and regexes in the include and omit paths fields.
