### ISSUE TITLE
Extrawide files cause HTML output to put line numbers before program

### ISSUE THREAD

**Issue by florence** [florence/cover#87]
See image [here](https://imgur.com/0helH56).

The file being run is https://github.com/florence/convex-hulls/blob/master/algos/test.rkt

**Comment by rpless** [comment]
Can I get a little more info? Like perhaps what browser this is happening in?

**Comment by florence** [comment]
It's happening in Chrome, Firefox, and Safari. But only on that file: The rest render as expected.

**Comment by florence** [comment]
I Figured out why that file: Some of the lines in that file are well beyond the screen width.

Bad Me.

**Comment by florence** [comment]
Given our plans for a "pretty" format, I would be okay with you closing this as "wontfix".
