### ISSUE TITLE
vector-ref: index is out of range with scribble document

### ISSUE THREAD

**Issue by jsmaniac** [florence/cover#90]
When running `raco cover` on a scribble document, I hit this `vector-ref: index is out of range` heisenbug, which was very weird to narrow down. Deleting some unused `(require racket)` and `(require (for-template typed/racket))` lines made the bug disappear initially, but once I had cleaned up bug2.rkt, the bug stayed after deleting these lines. The same thing occurred for other lines during the narrowing process I think.

Also, the bug disappears when moving `bug2.rkt`'s contents directly inside `bug1.rkt`, or as a submodule which is `require`d immediately after.

I tested this against the latest github commit 87f82e6 "Merge branch 'feature/uncovered-column'"

Initially, in the error message, the vector was much longer, and the out-of-range index too. As I removed lines from the file, they both gradually became smaller.

```
generating test coverage for ("/tmp/bug1.rkt")
vector-ref: index is out of range
  index: 9
  valid range: [0, 1]
  vector: '#(#f #f)
  context...:
   /home/georges/Install/DrRacket/cover/cover/cover.rkt:307:6: for-loop
   /home/georges/Install/DrRacket/cover/cover/cover.rkt:307:6: for-loop
   /home/georges/Install/DrRacket/cover/cover/cover.rkt:301:0: get-test-coverage17
   /home/georges/Install/DrRacket/cover/cover/raco.rkt:83:4
   /home/georges/Install/DrRacket/cover/cover/private/shared.rkt:28:0: with-intercepted-logging
   (submod /home/georges/Install/DrRacket/cover/cover/raco.rkt main): [running body]
   /usr/local/racket-6.2.900.10/collects/raco/raco.rkt: [running body]
```

File `bug1.rkt`:

```scheme
#lang scribble/lp2
@(require "bug2.rkt")
@(quux)
@chunk[<*>
       (module bar racket
         (define (foo val)
           (void)))]
```

File `bug2.rkt`:

```scheme
#lang racket
(define-syntax (quux stx) #'(list))
(provide quux)
```

**Comment by florence** [comment]
Repair pushed with d7f0d9a59763
